import json
import pandas as pd
import numpy as np
import os
import sys
import datetime

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from ingestion.data_ingestion import fetch_historical_data, get_stock_data

class ResearchLab:
    def __init__(self):
        with open('config/optimal_params.json', 'r') as f:
            self.optimal_params = json.load(f)
        
        # Load diagnostics if generated by updated optimizer
        try:
            with open('config/research_diagnostics.json', 'r') as f:
                self.diagnostics = json.load(f)
        except FileNotFoundError:
            self.diagnostics = {}

    def generate_coverage_report(self):
        """Measures strategy coverage across the stock universe."""
        print("\n=== 📊 STRATEGY COVERAGE ===")
        total_stocks = len(self.optimal_params)
        strategy_counts = {}
        
        for ticker, data in self.optimal_params.items():
            strat = data.get("strategy", "NONE")
            strategy_counts[strat] = strategy_counts.get(strat, 0) + 1
            
        for strat, count in sorted(strategy_counts.items(), key=lambda item: item[1], reverse=True):
            pct = (count / total_stocks) * 100
            print(f"{strat:15}: {count:3} stocks ({pct:.1f}%)")
            
        none_pct = (strategy_counts.get("NONE", 0) / total_stocks) * 100
        print(f"\nTargeting to reduce 'NONE' below 20%. Current: {none_pct:.1f}%")

    def profile_unsupported_behavior(self):
        """Understand stock behavior for rejected stocks (trend, volatility)."""
        print("\n=== 🔍 BEHAVIOUR PROFILES FOR 'NONE' STOCKS ===")
        rejected_tickers = [t for t, d in self.optimal_params.items() if d.get("strategy") == "NONE"]
        
        if not rejected_tickers:
            print("No rejected stocks to analyze!")
            return

        print(f"Fetching recent data to profile {len(rejected_tickers)} rejected stocks...")
        market_data = fetch_historical_data(rejected_tickers, period="1y")
        
        profiles = {"high_volatility": 0, "choppy_sideways": 0, "illiquid": 0}
        
        for ticker in rejected_tickers:
            df = get_stock_data(market_data, ticker)
            
            # CRITICAL FIX: Drop missing data. If the last row is NaN, the math fails silently!
            df = df.dropna(subset=['Close', 'High', 'Low'])
            
            if df.empty or len(df) < 50:
                profiles["illiquid"] += 1
                continue
            
            # Volatility calculation (ATR %)
            atr = (df['High'] - df['Low']).rolling(14).mean().iloc[-1]
            atr_pct = (atr / df['Close'].iloc[-1]) * 100
            
            # Trend calculation (50 vs 200 SMA proximity)
            sma_50 = df['Close'].rolling(50).mean().iloc[-1]
            sma_200 = df['Close'].rolling(200).mean().iloc[-1]
            
            if sma_200 == 0:
                continue
                
            trend_divergence = abs((sma_50 - sma_200) / sma_200) * 100
            
            # Categorize
            if atr_pct > 2.0:
                profiles["high_volatility"] += 1
            if trend_divergence < 8.0:
                profiles["choppy_sideways"] += 1
                
        print("Market Behavior currently unsupported by T_Raider:")
        print(f" - Highly Volatile (Needs wider stops / Options): {profiles['high_volatility']} stocks")
        print(f" - Choppy/Sideways (Needs Iron Condor / Range Bound strat): {profiles['choppy_sideways']} stocks")
        print(f" - Illiquid/Missing Data: {profiles['illiquid']} stocks")
    def generate_suggestions(self):
        """Discover missing strategy families dynamically."""
        print("\n=== 💡 FUTURE STRATEGY IDEAS ===")
        
        # Detect what strategies are currently active in the optimizer
        active_strats = set()
        for data in self.optimal_params.values():
            active_strats.add(data.get("strategy", "NONE"))
            
        print("Based on Behaviour Profiles and current system capabilities:")
        
        # 1. Choppy Stocks Logic
        if "RSI_DIVERGENCE" not in active_strats:
            print(" 1. Range-Bound Strategy (e.g., RSI Divergence) for Choppy stocks.")
        else:
            print(" ✅ RSI_DIVERGENCE is active, but choppy stocks still fail.")
            print("    -> Next Step: Directional trading fails here. Consider adding an Options module (e.g., Iron Condors) to farm premium on flat stocks.")

        # 2. Volatile Stocks Logic
        if "ATR_BREAKOUT" not in active_strats:
            print(" 2. High-Beta breakout strategy with ATR stops for Volatile stocks.")
        else:
            print(" ✅ ATR_BREAKOUT is active, but volatile stocks still fail.")
            print("    -> Next Step: The backtester's hard 10% stop-loss is likely choking out volatile trades before they run. Consider testing a 15% stop for high-beta assets.")
    
    def record_historical_knowledge(self):
        """Build historical knowledge to observe changes over time."""
        history_file = 'config/research_history.json'
        total_stocks = len(self.optimal_params)
        
        if total_stocks == 0:
            return
            
        current_stats = {
            "date": datetime.datetime.now().strftime("%Y-%m-%d"),
            "total_universe": total_stocks,
            "strategies": {}
        }
        
        for data in self.optimal_params.values():
            strat = data.get("strategy", "NONE")
            current_stats["strategies"][strat] = current_stats["strategies"].get(strat, 0) + 1
            
        # Load existing history
        try:
            with open(history_file, 'r') as f:
                history = json.load(f)
        except FileNotFoundError:
            history = []
            
        # Idempotency: If we run it twice today, overwrite today's entry rather than duplicating
        if history and history[-1]["date"] == current_stats["date"]:
            history[-1] = current_stats
        else:
            history.append(current_stats)
            
        os.makedirs('config', exist_ok=True)
        with open(history_file, 'w') as f:
            json.dump(history, f, indent=4)
            
        print(f"\n✅ Historical knowledge updated. Currently tracking {len(history)} optimization cycles.")

if __name__ == "__main__":
    lab = ResearchLab()
    lab.generate_coverage_report()
    lab.profile_unsupported_behavior()
    lab.generate_suggestions()  
    lab.record_historical_knowledge() 